version: "3.6"

services:
  satisfactory-server:
    build:
      context: .
      dockerfile: docker/satisfactory-server.Dockerfile
    restart: always
    user: "1000:1000"
    ports:
      - target: 15777
        published: 15777
        protocol: udp
      - target: 15000
        published: 15000
        protocol: udp
      - target: 7777
        published: 7777
        protocol: udp
    volumes:
      - ./SatisfactoryDedicatedServer:/home/steam/SatisfactoryDedicatedServer
      - ./SatisfactorySaveGames:/home/steam/.config/Epic/FactoryGame/Saved/SaveGames
    cap_drop:
      - ALL
